name: Build Windows Forms App

on:
  push:
    branches:
      - main  # Run this workflow on every push to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Framework
      run: |
        choco install visualstudio-installer
        vs_installer.exe install --quiet --add Microsoft.VisualStudio.Workload.ManagedDesktop

    - name: Restore dependencies
      run: nuget restore YourProject.sln

    - name: Build the project
      run: msbuild ST10122569_PROG7312_POE_Part1.sln /p:Configuration=Release
